# Generated by Django 4.2.9 on 2024-02-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("g_uno_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_ID",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
