# Generated by Django 5.0.1 on 2024-02-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_uno_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityordered',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
    ]
