# Generated by Django 4.2.9 on 2024-02-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("g_uno_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliveryreceipt",
            name="dr_payment_status",
            field=models.CharField(
                choices=[
                    ("Not Paid", "Not Paid"),
                    ("Partially Paid", "Partially Paid"),
                    ("Fully Paid", "Fully Paid"),
                ],
                default="Not Paid",
                max_length=15,
            ),
        ),
    ]
