# Generated by Django 5.0.1 on 2024-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_uno_app', '0002_deliveryreceipt_dr_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryreceipt',
            name='dr_vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
