# Generated by Django 4.2.9 on 2024-02-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("g_uno_app", "0002_alter_client_client_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryreceipt",
            name="client",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="g_uno_app.client",
            ),
        ),
    ]
