# Generated by Django 5.0.1 on 2024-01-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_uno_app', '0002_alter_deliveryreceipt_dr_amt_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='dr_amt_vat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='dr_amt_wo_vat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
