# Generated by Django 5.0.1 on 2024-01-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g_uno_app', '0004_alter_deliveryreceipt_dr_amt_vat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='dr_amt_vat',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='deliveryreceipt',
            name='dr_amt_wo_vat',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
